### ISSUE TITLE
No usar URL ABSOLUTAS desde PHP. 

### ISSUE THREAD

**Issue by jgorocica** [funveco/turecicla#2]
Es una muy mala práctica utilizar este tipo de código: 

`<script src="<?php echo $dato[0]; ?>js/base.js"></script>`
O
`<?php echo $dato[0]; ?>` 

En vez de eso, debes de usar URL relativas. Especificar la url desde el punto. Por ende quedaría así: 

`<script src="/js/base.js"></script>`

Te dejo un poco de información al respecto: 
[URL Absolutas y Relativas](https://librosweb.es/libro/xhtml/capitulo-4/enlaces-relativos-y-absolutos.html)

**Comment by funveco** [comment]
Gracias jgorocica por la información, lo tomaremos en cuenta...
